dist: trusty
language: node_js
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
node_js:
- '12'
before_install:
- npm install -g yarn
- yarn --version
install:
- yarn instal
script:
- yarn lint